# Generated by Django 5.2 on 2025-04-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('student_class', models.IntegerField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], verbose_name='Класс')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('plan', models.TextField(blank=True, verbose_name='План урока')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutor_app.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='Оценка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tutor_app.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tutor_app.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-lesson__date'],
            },
        ),
    ]
